### PR TITLE
jit: add jit_if_available option

### LINKED ISSUE #3: jit4lyfe fails on s390x
```rust
---- bytes::tests::jit4lyfe stdout ----
thread 'bytes::tests::jit4lyfe' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: JIT, code: -45, offset: None, message: "bad JIT option" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### PR DESCRIPTION
**Pull request by BurntSushi**
This commit adds a new builder option, `jit_if_available`, that is like
the existing `jit` option, but will silently fall back to the non-JIT
matcher if JIT compilation fails (and will also emit a debug log
message). This is useful for platforms that aren't supported by PCRE2's
JIT.

Fixes #3

### CODE REVIEW

File: src/bytes.rs [hunk 1]
```diff
@@ -1156,6 +1200,10 @@ mod tests {
     }
 
     #[test]
+    // I'm not sure what the platform support is for JIT, but it's probably
+    // not all of them. We really care about making sure it works on x86_64.
+    // We can add more platforms as folks request them.
+    #[cfg(target_arch = "x86_64")]
```
Comment (igor-raits) [inline src/bytes.rs]: I would prefer that it would be enabled wherever it is available rather than hardcoding..

Comment (igor-raits) [reply src/bytes.rs]: which is according to docs is:

```
  ARM 32-bit (v5, v7, and Thumb2)
  ARM 64-bit
  Intel x86 32-bit and 64-bit
  MIPS 32-bit and 64-bit
  Power PC 32-bit and 64-bit
  SPARC 32-bit
```

Comment (BurntSushi) [reply src/bytes.rs]: I mean sure, but I don't know what to write here. Do you?

Comment (BurntSushi) [reply src/bytes.rs]: I guess I could query PCRE2 at runtime inside the test, and if PCRE2 *believes* JIT is enabled, then we run the test, but otherwise skip it. How does that sound?

File: src/bytes.rs [hunk 2]
```diff
@@ -74,7 +74,17 @@ struct Config {
...
+}
+
+#[derive(Clone, Debug)]
+enum JITChoice {
+    /// Never do JIT compilation.
+    Never,
+    /// Always do JIT compilation and return an error if it fails.
+    Always,
+    /// Attempt to do JIT compilation but silently fall back to non-JIT.
+    Attempt,
```
Comment (igor-raits) [inline src/bytes.rs:87]: Probably better name would be `Auto`?

File: src/bytes.rs [hunk 3]
```diff
@@ -88,7 +98,7 @@ impl Default for Config {
             ucp: false,
             utf: false,
             utf_check: true,
-            jit: false,
+            jit: JITChoice::Never,
```
Comment (igor-raits) [inline src/bytes.rs:101]: why not auto?

File: src/bytes.rs (hunk 2 above)
Comment (BurntSushi) [reply src/bytes.rs:87]: Eh, this is an internal thing. It's not public.

File: src/bytes.rs (hunk 3 above)
Comment (BurntSushi) [reply src/bytes.rs:101]: Because as far as I can tell, PCRE2 doesn't auto-enable the JIT either. You need to at least specifically call `pcre2_jit_compile_8`, so I'm carrying over that API design choice.

File: src/ffi.rs [hunk 4]
```diff
@@ -13,6 +13,19 @@ use pcre2_sys::*;
 
 use error::Error;
 
+/// Returns true if and only if PCRE2 believes that JIT is enabled.
+pub fn is_jit_enabled() -> bool {
```
Comment (igor-raits) [inline src/ffi.rs]: I think `is_jit_available` is better..

Comment (BurntSushi) [reply src/ffi.rs]: SGTM!

**Comment by BurntSushi** [comment]
This PR is in `pcre2 0.1.1` on crates.io.
